version: 0.0
os: linux
files:
  - source: /Helloworld-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/Helloworld-0.0.1-SNAPSHOT.jar
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 60
      runas: root
