#!/bin/bash
apt update
apt install -y htop

#apt-get install locales
#apt install -y yum
#apt install -y apache2
#
#sudo apt install -y openjdk-8-jre-headless
#apt install -y default-jre
#apt install -y maven
