#!/bin/bash
sudo yum -y update
sudo yum install -y htop

#apt-get install locales
#apt install -y yum
#apt install -y apache2
#
#sudo apt install -y openjdk-8-jre-headless
sudo yum install -y jre
sudo yum install -y maven
